---
- hosts: escapestring

  vars_files:
    - ./vars/deploy_vault.yml
    - ./vars/vars.yml
    - ./vars/deploy_vars.yml

  roles:
    - carlosbuenosvinos.ansistrano-deploy

  vars:
    ansistrano_deploy_to: "{{ project_root_dir }}"
    ansistrano_deploy_via: git
    ansistrano_git_repo: "https://github.com/liweiyi88/integration.git"
    ansistrano_git_branch: master
    ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy/after-symlink-shared.yml"
    release_console_path: "{{ ansistrano_release_path.stdout }}/bin/console"
    release_var_path: "{{ ansistrano_release_path.stdout }}/var"

  environment:
    SYMFONY_ENV: prod
